### ISSUE TITLE
Replace placeholder Treasury addresses.

### ISSUE THREAD

**Issue by gjhiggins** [heliumchain/helium#4]
In https://github.com/heliumchain/helium/blob/master/src/chainparams.cpp#L2350 and https://github.com/heliumchain/helium/blob/d4be3752fb564c84a83e64dd977bac2701f3eb6b/src/chainparams.cpp#L2499 and https://github.com/heliumchain/helium/blob/d4be3752fb564c84a83e64dd977bac2701f3eb6b/src/chainparams.cpp#L2608

**Comment by faetos** [comment]
Changed the addresses and handed over associated items

**Comment by faetos** [comment]
didn't fix it like I thought

**Comment by gjhiggins** [comment]
Any change to the genesis tx will change the merkel root hash and the genesis block hash, so a new genesis block has to be created. Would be a good idea at that point to pull in a new Bitcoin block nHeight and hash to update the pzsTimeStamp.

**Comment by faetos** [comment]
Replaced them and changed the block: const char* pszTimestamp = "Bitcoin Block #531843: 00000000000000000004b8ac34227fc1932aaa01bf78e744dae90c15089320e1"

**Comment by faetos** [comment]
Final set:
// Mainnet --- nonce: 851930 time: 1520801782 hash: 0x00000289d5c33bbc11a166ee53f3e76aa80863ffbc10f22b2484ffc40f7357b2 merklehash: 0x41af082a5c40201a598b994218ceb4aabc59a70999009f6e1bf6f9e063b794b9
// Testnet --- nonce: 1497998 time: 1520801782 hash: 0x00000ad9f74009abda4c38fe49f4cf1c37cc8c956a931e669313cef5739157f3 merklehash: 0x53c6673d08fd145d707ccd623c5c254f1e4a283b1321662ca991dd9231d9b526
// Regtestnet --- nonce: 5 time: 1520801782 hash: 0x545594cf835ead5266cd10f0d6f5f8497f69910cd781940d53590bd36bc20d14 merklehash: 0x41af082a5c40201a598b994218ceb4aabc59a70999009f6e1bf6f9e063b794b9
