### ISSUE TITLE
helium qt window sizing

### ISSUE THREAD

**Issue by dacaldera** [heliumchain/helium#63]
Issue: QT wallet window not resizable, which effectively cuts off botttom portion of wallet on 16:9 displays. Maximize window feature is disabled. Inability to see and payments button. 
Tested on display resolution: 1366x768 (16:9) confirmed

The qt-wallet window should allow dynamic resizing by clicking and dragging the borders. The "maximize" option should be enabled to allow full-screen wallet, which could fix the problem temporarily. 

Currently, the "maximize" button is disabled. The window does not allow for dynamically scaling down the window below default. (scaling up the window more than default does work). 

![screenshot from 2018-10-28 12-15-49](https://user-images.githubusercontent.com/31627084/47619315-4d8ab980-daab-11e8-96c4-c9af645ae4a8.png)

using Helium Core version v0.15.2 (64-bit) Linux

    OS: Ubuntu 18.04
    Monitor Resolution: 1366x768

**Comment by trollboxteela** [comment]
Thank you for reporting. Just tested on ubuntu 18.04 and it seems that dynamic resizing of the wallet (and maximizing) is not working for resolutions under 1440x810. Tested the PIVX client too and it does the same.
