### ISSUE TITLE
[Meta] Issue labels

### ISSUE THREAD

**Issue by gjhiggins** [heliumchain/helium#7]
Use labels to add a well-designed semantic structure to the issues and update the issue template - which is actually: https://github.com/heliumchain/helium/blob/master/.github/ISSUE_TEMPLATE.md

This issue tracker is only for technical issues related to Helium Core.
General Helium questions and/or support requests and are best directed to the [Helium Slack](https://onetrollbox.slack.com).

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Helium Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by faetos** [comment]
changed the names from PIVX to Helium. Also, updated the source

**Comment by faetos** [comment]
Completed - added tags to help identify issues easier
